DROP TABLE IF EXISTS users;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  first VARCHAR(200) NOT NULL,
  last VARCHAR(200) NOT NULL,
  email VARCHAR(300) UNIQUE NOT NULL,
  password VARCHAR(200) NOT NULL,
  profilepicurl VARCHAR(200),
  bio VARCHAR(400),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
